### PR TITLE
Introduce stateless arrow function components

### PR DESCRIPTION
**Pull request by andrejkn**
Changed the Counter into a stateless component!

### CODE REVIEW

**Comment by andrejkn** [comment]
@rbrander @neilff please do a quick review and let me know if it's ok?

**Comment by neilff** [comment]
Looks good, wondering if we should break down components further into `Button`, and such.

**Comment by andrejkn** [comment]
@neilff we should be doing that for our projects but for this seed repo it's ok to have only one component. @SethDavenport might have an input on that ?

**Comment by SethDavenport** [comment]
Re components: I leave it up to you guys.

**Comment by neilff** [comment]
We can solve it in a later PR if we do go that route, I think this is a good start for stateless components

**Pull request merged**
